require('dotenv').config();
const { initDB, getDB } = require('./src/models/db');
initDB();
const db = getDB();
const all = db.prepare('SELECT id, symbol, order_id, status FROM crypto_positions').all();
console.log('ALL:', all.length);
all.forEach(r => console.log(r.id, r.symbol, (r.order_id||'').substring(0,25), r.status));
const c = db.prepare("UPDATE crypto_positions SET status='CLOSED', reason='paper cleanup' WHERE order_id LIKE 'PAPER%' AND status='OPEN'").run();
console.log('Closed PAPER:', c.changes);
const open = db.prepare("SELECT id, symbol, order_id FROM crypto_positions WHERE status='OPEN'").all();
console.log('Still OPEN:', open.length);
open.forEach(r => console.log(r.id, r.symbol, (r.order_id||'').substring(0,25)));
