#!/bin/bash
cd /var/www/autotrader
echo "============================================"
echo "  AUDITORÍA COMPLETA DE PnL"
echo "============================================"
echo ""
echo "=== 1. TODAS las posiciones cerradas (detalle) ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, current_price, pnl, status, substr(reason,1,80), created_at, closed_at FROM crypto_positions WHERE status='CLOSED' ORDER BY id;"
echo ""
echo "=== 2. Posiciones con PnL = 0 (sospechosas) ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, current_price, pnl, substr(reason,1,80) FROM crypto_positions WHERE status='CLOSED' AND (pnl = 0 OR pnl IS NULL);"
echo ""
echo "=== 3. Posiciones ABIERTAS ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, current_price, stop_loss, take_profit FROM crypto_positions WHERE status='OPEN';"
echo ""
echo "=== 4. PnL registrado vs PnL REAL (recalculado) ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, current_price, pnl as pnl_registrado, ROUND((current_price - entry_price) * quantity, 4) as pnl_real, CASE WHEN ABS(pnl - (current_price - entry_price) * quantity) > 0.01 THEN 'DIFERENCIA' ELSE 'OK' END as check_status FROM crypto_positions WHERE status='CLOSED' AND current_price > 0;"
echo ""
echo "=== 5. Resumen de fees estimados ==="
echo "Binance cobra 0.1% por trade (buy+sell = 0.2% roundtrip)"
sqlite3 data/autotrader.db "SELECT COUNT(*) as total_trades, ROUND(SUM(quantity * entry_price), 2) as volumen_compra, ROUND(SUM(quantity * entry_price) * 0.002, 2) as fees_estimados_roundtrip FROM crypto_positions WHERE status='CLOSED';"
echo ""
echo "=== 6. PnL TOTAL registrado ==="
sqlite3 data/autotrader.db "SELECT ROUND(SUM(pnl), 4) as pnl_db FROM crypto_positions WHERE status='CLOSED';"
echo ""
echo "=== 7. PnL REAL recalculado (sin fees) ==="
sqlite3 data/autotrader.db "SELECT ROUND(SUM((current_price - entry_price) * quantity), 4) as pnl_real FROM crypto_positions WHERE status='CLOSED' AND current_price > 0;"
echo ""
echo "=== 8. Posiciones PAPER (order_id empieza con PAPER) ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, pnl, order_id, substr(reason,1,60) FROM crypto_positions WHERE order_id LIKE 'PAPER%' OR order_id LIKE 'paper%';"
echo ""
echo "=== 9. Posiciones sin order_id (posibles fantasma) ==="
sqlite3 data/autotrader.db "SELECT id, symbol, quantity, entry_price, pnl, order_id, status FROM crypto_positions WHERE order_id = '' OR order_id IS NULL;"
